### ISSUE TITLE
Plex url root

### ISSUE THREAD

**Issue by turboblip** [SpaceK33z/movieo-to-plex#11]
![screen shot 2016-12-15 at 1 14 48 pm](https://cloud.githubusercontent.com/assets/24595526/21242298/7e8374ac-c2c8-11e6-91be-4665c2ce373f.png)

I do not understand how to find this, any help would be greatly appreciated.

"Plex url root:  
In Plex Web, open the DevTools (F12). You should see one or two messages about "Testing connection". Use the one with your external IP. Copy and paste the URL after the message here. Example: https://85-123-211-72.qe23e81fd3dcdda73ff82cxxxb446b0ff.plex.direct:32400"

**Comment by SpaceK33z** [comment]
Ah, the description isn't clear on that you should look into the "Console". Click on the Console tab, and then follow the instructions.

Sidenote: I'm working on make Plex easier to setup in #10.

**Comment by turboblip** [comment]
Got it, thank you!
