### ISSUE TITLE
Feature: Adding custom sites

### ISSUE THREAD

**Issue by SunsparcSolaris** [SpaceK33z/movieo-to-plex#169]
I had a thought this morning while browsing my favorite torrent site that it would be nice if I could pop up a box somehow and search/add something to Sonarr/Radarr directly without having to browse over to those instances, do what I need to do, then go back to the site.

When I stumbled upon Web to Plex, I thought I had found what I wanted but I see that it only supports a dedicated list of sites.

Would it be possible to add a feature where we can whitelist a custom site for Sonarr/Radarr search to appear on?

**Comment by Ephellon** [comment]
Yes that's possible, please see the Wiki on how to make a site supportable. Ensure you're using `v4.1` or later.

**Comment by Ephellon** [comment]
@SunsparcSolaris [Writing a Plugin](https://github.com/SpaceK33z/web-to-plex/wiki/Writing-a-Plugin)

**Comment by Ephellon** [comment]
Please note, the project is still in work (though currently in hiatus due to COVID-19), and will be updated in a few months (if all goes well)

**Comment by Ephellon** [comment]
Closed, as this feature already exists
