### ISSUE TITLE
Issue: Letterboxd Plex Error (Chrome)

### ISSUE THREAD

**Issue by adamkesher** [SpaceK33z/movieo-to-plex#171]
**Describe the bug**

In Chrome, Letterboxd is showing "Plex Error," instead of the "On Plex" button that appears on Trakt for example.
**To Reproduce**

1. Go to https://letterboxd.com
2. Click on, a movie in the main feed that I have on my Plex server, https://letterboxd.com/film/ordinary-people/
3. Scroll down to "Where to Watch"
4. See error "Plex Error"

**Expected behavior**

Expected the "On Plex" button to appear where "Plex Error" appears as I have the movie and have granted access.
**Screenshots**

<img width="239" alt="Chrome Web to Plex Error" src="https://user-images.githubusercontent.com/37488763/80316653-d7583780-87b3-11ea-9746-c3ea2efcb21c.png">
<img width="544" alt="Chrome Plex Error from console" src="https://user-images.githubusercontent.com/37488763/80316707-3158fd00-87b4-11ea-8a84-d32177aaf406.png">

**Extension Information**
 - Version: Web to Plex 3.4
 - Source: Chrome Web Store extensions
 - Browser: Chrome 81.0.4044.122 (Official Build) (64-bit)
 - Operating System: MacOS 10.15.4

**Additional comments**

I have tried logging out and logging back in with my Plex credentials. I've also tried uninstalling/reinstalling the extension. Tried restarting browser, restarting system. Tried different movies to make sure it wasn't a one off case. But I always see the "Plex Error" for Letterboxd.

The extension works for me on the other supported sites.

**Comment by Ephellon** [comment]
Update to `v4.1`

Where are you all getting your information (this is the 8th issue to be outdated)?

**Comment by Ephellon** [comment]
I'll add a notice that `v4.1` is the most recent

**Comment by adamkesher** [comment]
So sorry. Went through the Chrome store to the outdated plug-in. Will close this request for the old version. Thank you.

**Comment by Ephellon** [comment]
No problem. I can't change the old version (as it's controlled by @SpaceK33z), I'll try getting that sorted out

**Comment by Ephellon** [comment]
Please use the links in the Wiki, or on the README for the most recent version @adamkesher
