### ISSUE TITLE
Insecure CouchPotato API calls don't work

### ISSUE THREAD

**Issue by SpaceK33z** [SpaceK33z/movieo-to-plex#2]
Requests to a `http` CouchPotato API fail because of mixed content; Movieo uses `https`.

I need to find a way to bypass this. It could be fixed if the request would not take place in the content script, but in a background script.

**Comment by SpaceK33z** [comment]
Oh great, to fix this I need to make the request to CouchPotato in a background page. However, I can't just make random requests in a background permission. You need to add the URL you want to do a request to in the permissions. However, our URL is dynamic (it's a user option)...

For now I can fix this with the `<all_urls>` permission, but need to find a better fix...

**Comment by R0GGER** [comment]
same error here... v2.3
It doesn't work with http links.

**Comment by SpaceK33z** [comment]
@R0GGER, hey, I just checked this for you, but it works for me with a http link. Do you have any more info? Is this with a reverse proxy or just a direct IP? I tested it with a direct IP.
